name: melon_metrics
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flame: ^1.21.0
  flutter:
    sdk: flutter
  health: ^11.1.0
  http: ^1.2.2
  isar:
    hosted: https://pub.isar-community.dev
    version: ^3.1.8
  isar_flutter_libs:
    hosted: https://pub.isar-community.dev
    version: ^3.1.8
  provider: ^6.1.2
  table_calendar: ^3.0.8
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: any
  isar_generator:
    hosted: https://pub.isar-community.dev
    version: ^3.1.8

flutter:
  uses-material-design: true
  assets:
    - assets/good.png
    - assets/cheer.gif
    - assets/images/owl/
